### ISSUE TITLE
Can't run example json-metadata-tutorial.ipynb from datachain-examples on colab.

### ISSUE THREAD

**Issue by dberenbaum** [iterative/datachain-examples#14]
See https://discord.com/channels/485586884165107732/563406153334128681/1277944330576990230.

**Comment by dberenbaum** [comment]
Note that even with `anon=True`, I am seeing errors:

```python
> next(DataChain.from_storage('gs://datachain-demo/dogs-and-cats/cat.1009.jpg', type='image', anon='true').collect("file")).read()
ERROR:gcsfs:_request out of retries on exception: ("Failed to retrieve http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/?recursive=true from the Google Compute Engine metadata service. Status: 404 Response:\nb''", <google.auth.transport.requests._Response object at 0x7d7b1fc80460>)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/google/auth/compute_engine/credentials.py", line 128, in refresh
    self._retrieve_info(request)
  File "/usr/local/lib/python3.10/dist-packages/google/auth/compute_engine/credentials.py", line 101, in _retrieve_info
    info = _metadata.get_service_account_info(
  File "/usr/local/lib/python3.10/dist-packages/google/auth/compute_engine/_metadata.py", line 323, in get_service_account_info
    return get(request, path, params={"recursive": "true"})
  File "/usr/local/lib/python3.10/dist-packages/google/auth/compute_engine/_metadata.py", line 248, in get
    raise exceptions.TransportError(
google.auth.exceptions.TransportError: ("Failed to retrieve http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/?recursive=true from the Google Compute Engine metadata service. Status: 404 Response:\nb''", <google.auth.transport.requests._Response object at 0x7d7b1fc80460>)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gcsfs/retry.py", line 126, in retry_request
    return await func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/gcsfs/core.py", line 431, in _request
    headers=self._get_headers(headers),
  File "/usr/local/lib/python3.10/dist-packages/gcsfs/core.py", line 408, in _get_headers
    self.credentials.apply(out)
  File "/usr/local/lib/python3.10/dist-packages/gcsfs/credentials.py", line 187, in apply
    self.maybe_refresh()
  File "/usr/local/lib/python3.10/dist-packages/gcsfs/credentials.py", line 182, in maybe_refresh
    self.credentials.refresh(req)
  File "/usr/local/lib/python3.10/dist-packages/google/auth/compute_engine/credentials.py", line 134, in refresh
    raise new_exc from caught_exc
google.auth.exceptions.RefreshError: ("Failed to retrieve http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/?recursive=true from the Google Compute Engine metadata service. Status: 404 Response:\nb''", <google.auth.transport.requests._Response object at 0x7d7b1fc80460>)
Preparing: 1 rows [00:00, 148.76 rows/s]
Processed: 1 rows [00:00, 280.89 rows/s]
Cleanup: 2 tables [00:00, 1578.29 tables/s]
ERROR:gcsfs:_request out of retries on exception: ("Failed to retrieve http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/?recursive=true from the Google Compute Engine metadata service. Status: 404 Response:\nb''", <google.auth.transport.requests._Response object at 0x7d7b1f1e6410>)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/google/auth/compute_engine/credentials.py", line 128, in refresh
    self._retrieve_info(request)
  File "/usr/local/lib/python3.10/dist-packages/google/auth/compute_engine/credentials.py", line 101, in _retrieve_info
    info = _metadata.get_service_account_info(
  File "/usr/local/lib/python3.10/dist-packages/google/auth/compute_engine/_metadata.py", line 323, in get_service_account_info
    return get(request, path, params={"recursive": "true"})
  File "/usr/local/lib/python3.10/dist-packages/google/auth/compute_engine/_metadata.py", line 248, in get
    raise exceptions.TransportError(
google.auth.exceptions.TransportError: ("Failed to retrieve http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/?recursive=true from the Google Compute Engine metadata service. Status: 404 Response:\nb''", <google.auth.transport.requests._Response object at 0x7d7b1f1e6410>)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gcsfs/retry.py", line 126, in retry_request
    return await func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/gcsfs/core.py", line 431, in _request
    headers=self._get_headers(headers),
  File "/usr/local/lib/python3.10/dist-packages/gcsfs/core.py", line 408, in _get_headers
    self.credentials.apply(out)
  File "/usr/local/lib/python3.10/dist-packages/gcsfs/credentials.py", line 187, in apply
    self.maybe_refresh()
  File "/usr/local/lib/python3.10/dist-packages/gcsfs/credentials.py", line 182, in maybe_refresh
    self.credentials.refresh(req)
  File "/usr/local/lib/python3.10/dist-packages/google/auth/compute_engine/credentials.py", line 134, in refresh
    raise new_exc from caught_exc
google.auth.exceptions.RefreshError: ("Failed to retrieve http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/?recursive=true from the Google Compute Engine metadata service. Status: 404 Response:\nb''", <google.auth.transport.requests._Response object at 0x7d7b1f1e6410>)

---------------------------------------------------------------------------

TransportError                            Traceback (most recent call last)

[/usr/local/lib/python3.10/dist-packages/google/auth/compute_engine/credentials.py](https://localhost:8080/#) in refresh(self, request)
    127         try:
--> 128             self._retrieve_info(request)
    129             self.token, self.expiry = _metadata.get_service_account_token(

26 frames

TransportError: ("Failed to retrieve http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/?recursive=true from the Google Compute Engine metadata service. Status: 404 Response:\nb''", <google.auth.transport.requests._Response object at 0x7d7b1f1e6410>)


The above exception was the direct cause of the following exception:

RefreshError                              Traceback (most recent call last)

<decorator-gen-157> in _request(self, method, path, headers, json, data, *args, **kwargs)

[/usr/local/lib/python3.10/dist-packages/google/auth/compute_engine/credentials.py](https://localhost:8080/#) in refresh(self, request)
    132         except exceptions.TransportError as caught_exc:
    133             new_exc = exceptions.RefreshError(caught_exc)
--> 134             raise new_exc from caught_exc
    135 
    136     @property

RefreshError: ("Failed to retrieve http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/?recursive=true from the Google Compute Engine metadata service. Status: 404 Response:\nb''", <google.auth.transport.requests._Response object at 0x7d7b1f1e6410>)
```

**Comment by shcheklein** [comment]
@dberenbaum can you to try to restart the kernel / env after you do `anon=True`? I think the session object is caching the storage config (which is a different thing to discuss if that the case)

**Comment by dberenbaum** [comment]
Thanks @shcheklein, that fixes my comment! Still need to add `anon=True` throughout the notebook, though.

**Comment by shcheklein** [comment]
@dberenbaum I think btw one single place is enough (unless we expect people to start from the middle). Are you going to do this or you want me to update it? (feel free to reassign please).

Also, if you have time - please think about this in general - is it fine that we are caching it this way? Is it an inevitable "evil" in notebooks?

**Comment by ayasyrev** [comment]
After set `anon=True` and restart session, `!datachain ls "gs://datachain-demo/dogs-and-cats/*1009*"` become works too.
Later in code
`uri = "gs://datachain-demo/openimages-jsonl/open_images_validation_localized_narratives.jsonl"
DataChain.from_storage(uri).print_jsonl_schema(model_name="Narrative").exec()`
works without `anon=True`

**Comment by dberenbaum** [comment]
@ayasyrev Do you want to take this? Just let us know so we know whether to fix or leave for you.

**Comment by shcheklein** [comment]
Should be fixed by https://github.com/iterative/datachain-examples/commit/37fd9f34ee5aaffbf55984c2162a478fb012027e
