### ISSUE TITLE
`TransportError` in "Fine tuning CLIP for image captions" notebook

### ISSUE THREAD

**Issue by amrzv** [iterative/datachain-examples#9]
Hello.
When running [clip_fine_tuning.ipynb](https://colab.research.google.com/github/iterative/datachain-examples/blob/main/multimodal/clip_fine_tuning.ipynb#scrollTo=c40feba6-929a-4a0f-af8e-028c048a644c) notebook in colab
the error raised
```bash
RefreshError: ("Failed to retrieve http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/?recursive=true from the Google Compute Engine metadata service. Status: 404 Response:\nb''", <google.auth.transport.requests._Response object at 0x792cde6acd90>)
```
on the cell with
```python
img_dc.show(3)
```

Full traceback
```bash
ERROR:gcsfs:_request out of retries on exception: ("Failed to retrieve http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/?recursive=true from the Google Compute Engine metadata service. Status: 404 Response:\nb''", <google.auth.transport.requests._Response object at 0x792cdef5feb0>)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/google/auth/compute_engine/credentials.py", line 128, in refresh
    self._retrieve_info(request)
  File "/usr/local/lib/python3.10/dist-packages/google/auth/compute_engine/credentials.py", line 101, in _retrieve_info
    info = _metadata.get_service_account_info(
  File "/usr/local/lib/python3.10/dist-packages/google/auth/compute_engine/_metadata.py", line 323, in get_service_account_info
    return get(request, path, params={"recursive": "true"})
  File "/usr/local/lib/python3.10/dist-packages/google/auth/compute_engine/_metadata.py", line 248, in get
    raise exceptions.TransportError(
google.auth.exceptions.TransportError: ("Failed to retrieve http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/?recursive=true from the Google Compute Engine metadata service. Status: 404 Response:\nb''", <google.auth.transport.requests._Response object at 0x792cdef5feb0>)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gcsfs/retry.py", line 126, in retry_request
    return await func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/gcsfs/core.py", line 431, in _request
    headers=self._get_headers(headers),
  File "/usr/local/lib/python3.10/dist-packages/gcsfs/core.py", line 408, in _get_headers
    self.credentials.apply(out)
  File "/usr/local/lib/python3.10/dist-packages/gcsfs/credentials.py", line 187, in apply
    self.maybe_refresh()
  File "/usr/local/lib/python3.10/dist-packages/gcsfs/credentials.py", line 182, in maybe_refresh
    self.credentials.refresh(req)
  File "/usr/local/lib/python3.10/dist-packages/google/auth/compute_engine/credentials.py", line 134, in refresh
    raise new_exc from caught_exc
google.auth.exceptions.RefreshError: ("Failed to retrieve http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/?recursive=true from the Google Compute Engine metadata service. Status: 404 Response:\nb''", <google.auth.transport.requests._Response object at 0x792cdef5feb0>)
Listing gs://datachain-demo: 0 objects [00:00, ? objects/s]ERROR:gcsfs:_request out of retries on exception: ("Failed to retrieve http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/?recursive=true from the Google Compute Engine metadata service. Status: 404 Response:\nb''", <google.auth.transport.requests._Response object at 0x792cde6acd90>)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/google/auth/compute_engine/credentials.py", line 128, in refresh
    self._retrieve_info(request)
  File "/usr/local/lib/python3.10/dist-packages/google/auth/compute_engine/credentials.py", line 101, in _retrieve_info
    info = _metadata.get_service_account_info(
  File "/usr/local/lib/python3.10/dist-packages/google/auth/compute_engine/_metadata.py", line 323, in get_service_account_info
    return get(request, path, params={"recursive": "true"})
  File "/usr/local/lib/python3.10/dist-packages/google/auth/compute_engine/_metadata.py", line 248, in get
    raise exceptions.TransportError(
google.auth.exceptions.TransportError: ("Failed to retrieve http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/?recursive=true from the Google Compute Engine metadata service. Status: 404 Response:\nb''", <google.auth.transport.requests._Response object at 0x792cde6acd90>)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gcsfs/retry.py", line 126, in retry_request
    return await func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/gcsfs/core.py", line 431, in _request
    headers=self._get_headers(headers),
  File "/usr/local/lib/python3.10/dist-packages/gcsfs/core.py", line 408, in _get_headers
    self.credentials.apply(out)
  File "/usr/local/lib/python3.10/dist-packages/gcsfs/credentials.py", line 187, in apply
    self.maybe_refresh()
  File "/usr/local/lib/python3.10/dist-packages/gcsfs/credentials.py", line 182, in maybe_refresh
    self.credentials.refresh(req)
  File "/usr/local/lib/python3.10/dist-packages/google/auth/compute_engine/credentials.py", line 134, in refresh
    raise new_exc from caught_exc
google.auth.exceptions.RefreshError: ("Failed to retrieve http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/?recursive=true from the Google Compute Engine metadata service. Status: 404 Response:\nb''", <google.auth.transport.requests._Response object at 0x792cde6acd90>)
Listing gs://datachain-demo: 0 objects [00:34, ? objects/s]
---------------------------------------------------------------------------
TransportError                            Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/google/auth/compute_engine/credentials.py](https://localhost:8080/#) in refresh(self, request)
    127         try:
--> 128             self._retrieve_info(request)
    129             self.token, self.expiry = _metadata.get_service_account_token(

29 frames
TransportError: ("Failed to retrieve http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/?recursive=true from the Google Compute Engine metadata service. Status: 404 Response:\nb''", <google.auth.transport.requests._Response object at 0x792cde6acd90>)

The above exception was the direct cause of the following exception:

RefreshError                              Traceback (most recent call last)
<decorator-gen-157> in _request(self, method, path, headers, json, data, *args, **kwargs)

[/usr/local/lib/python3.10/dist-packages/google/auth/compute_engine/credentials.py](https://localhost:8080/#) in refresh(self, request)
    132         except exceptions.TransportError as caught_exc:
    133             new_exc = exceptions.RefreshError(caught_exc)
--> 134             raise new_exc from caught_exc
    135 
    136     @property

RefreshError: ("Failed to retrieve http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/?recursive=true from the Google Compute Engine metadata service. Status: 404 Response:\nb''", <google.auth.transport.requests._Response object at 0x792cde6acd90>)
```

**Comment by ayasyrev** [comment]
Same error in colab.

**Comment by shcheklein** [comment]
I think it should be fixed now - in https://github.com/iterative/datachain-examples/commit/e20dbd27c2470383088f98db186cb6cf336f5582

There is a different one though, that I'm getting - `UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7ad29e402f20>`in the:

```python
example = sample_results[0]
example[0].read()
```

I'm looking into that as well.

Thanks folks for the report!

**Comment by shcheklein** [comment]
Fixed the pillow issue this in the main branch (I hope). It seems it is pre-installed on Colab, and an outdated version is loaded.
